version: 1.0.{build}
image: Visual Studio 2015

build: off

environment:
  global:
    # Avoid long paths on Windows
    STACK_ROOT: "c:\\s"
    STACK_WORK: ".w"
    WORK_DIR: "c:\\w"


before_test:
# Avoid long paths not to each MAX_PATH of 260 chars
- xcopy /q /s /e /r /k /i /v /h /y C:\projects\tar-conduit "%WORK_DIR%"
- cd "%WORK_DIR%"


# Install stack
- ps: Start-FileDownload http://www.stackage.org/stack/windows-x86_64 -FileName stack.zip
- 7z x stack.zip stack.exe

# Install cache-s3 and try to restore cache
- ps: Start-FileDownload https://s3.amazonaws.com/lehins-ci-cache/cache-s3_windows-x86_64.exe -FileName cache-s3.exe
- cache-s3 -b $S3_BUCKET --prefix=tar-conduit --suffix=windows -v debug restore stack --base-branch=master
- cache-s3 -b $S3_BUCKET --prefix=tar-conduit --suffix=windows -v debug restore stack work --base-branch=master


test_script:
  - cd "%WORK_DIR%"
  - stack --verbosity warn setup --no-reinstall > nul
  - stack test tar-conduit:tests
      -j 2
      --no-terminal
      --local-bin-path %WORK_DIR%
      --no-haddock-deps
      --work-dir %STACK_WORK%


after_test:
- cache-s3 -b $S3_BUCKET --prefix=tar-conduit --suffix=windows -v debug save stack
- cache-s3 -b $S3_BUCKET --prefix=tar-conduit --suffix=windows -v debug save stack work

notifications:
  - provider: Email
    to:
      - lehins@yandex.ru
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
