name:        tar-conduit
version:     0.1.1
synopsis:    Parse tar files using conduit for streaming
description: Please see README.md. This is just filler to avoid warnings.
category:    Data Conduit
author:      Michael Snoyman
maintainer:  michael@snoyman.com, bartavelle@gmail.com
license:     MIT
github:      snoyberg/tar-conduit

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4.7 && <5
- bytestring
- conduit-combinators >=1.0.8.1

library:
  source-dirs: src

# test-suite tar-conduit-test
#   type:                exitcode-stdio-1.0
#   hs-source-dirs:      test
#   main-is:             Spec.hs
#   build-depends:       base
#                      , hspec
#                      , tar-conduit
#                      , conduit-extra
#                      , conduit-combinators
#   ghc-options:         -threaded -rtsopts -with-rtsopts=-N
#   default-language:    Haskell2010
